# -*- coding: utf-8 -*-
"""13.03.2023-Exercicio 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Jg6PZE_PlnlNdLqEGKgiyYT6G8S0Lf4

1)Escreva um programa que pergunte o salário do funcionário e calcule o valor do aumento. Para salários superiores a R$ 1.250,00,
"""

sal = float(input("Digite o valor do salário: "))
res = sal+(sal*0.10)
if sal > 1250:
  #print("Aumento: 10% \nNovo Salário:",sal+(sal*0.10))
  print(f"Aumento: 10% \nNovo Salário: {res}")
else:
  #print("Aumento: 15% \nNovo Salário:",sal+(sal*0.15))
  print(f"Aumento: 15% \nNovo Salário: {res}")

"""2)Escreva um programa que leia dois números e que pergunte qual operação você deseja realizar.
Você deve poder calcular soma (+), subtração (-), multiplicação (*) e divisão (/). Exiba o resultado da operação solicitada
"""

num1= int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))


conta=input("Digite a operação desejada:")

if conta == '+':
  print(" %i + %i = %i"%(num1,num2,num1+num2))

elif conta == '-':
  print(" %i - %i = %i"%(num1,num2,num1-num2))

elif conta == '/':
  if num2 == 0:
    print("Impossível dividir por zero")
  else:
    print(" %i / %i = %i"%(num1,num2,num1/num2))

elif conta == '*':
  print(" %i x %i = %i"%(num1,num2,num1*num2))

"""3)Escreva um programa para aprovar o empréstimo bancário para compra de uma casa. O programa deve perguntar o valor da casa a comprar, o salário e a quantidade de anos a pagar. O valor da prestação mensal não pode ser superior a 30% do salário. Calcule o valor da prestação como sendo o valor da casa a comprar dividido pelo número de meses a pagar."""

casa = (float(input("Digite o valor da casa:")))
sal = (float(input("Digite o valor do salário:")))
anos = (int(input("Digite a quantidade de anos a pagar:")))


res = casa/(anos*12)

if res > (0.30*sal):
  print("\nPrestações: R$ %.2f \nSalário: R$ %i  \nValor da casa: R$ %.2f \nEmprestimo negado"%(res,sal,casa))

else:
  print("\nPrestações: R$ %.2f \nSalário: R$ %i  \nValor da casa: R$ %.2f \nEmprestimo Aprovado"%(res,sal,casa))

"""5)Faça um algoritmo para ler: quantidade atual em estoque, quantidade máxima em estoque e quantidade mínima em estoque de um produto. Calcular e escrever a quantidade média ((quantidade média = quantidade máxima + quantidade mínima)/2). Se a quantidade em estoque for maior ou igual a quantidade média escrever a mensagem 'Não efetuar compra', senão escrever a mensagem 'Efetuar compra'.  

"""

quantA = int(input("Digite a quantidade em estoque:"))
quantM = int(input("Digite a capacidade do estoque:"))
quantMi = int(input("Digite a quantiade minima de estoque:"))


quantMed = (quantM+quantMi)/2

if quantA > quantMed:

  print("Não efetuar compra")

elif quantA == quantMed:
  print("Não efetuar compra")

else:
  print("Efetuar compra")