# -*- coding: utf-8 -*-
"""1-Exemplo 1 - 20.03.24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bho6hUvOZtC5AEIeunswmoRF3HBk4sqf

Estruturas de Repetição

- for/range

   -sintaxe: for contador in  range(repetições):
                  comando a ser repetido
   - prestar atenção na identação
"""

for i in range(5):
  #identação
  print("Olá mundo")

"""for contador in range(inicio, termino,passo)"""

#contando de 2 em 2, começando por 100 até 110
for i in range(100,110,2):
  print(i)

"""for com variáveis contadoras e variáveis acumuladoras

-exemplo: Cadastrar o salário e o sexo de 10 pessoas. Ao final imprimir o número de mulheres e o total de salários  e o número homens com o total de salário
"""

totalH = 0
totalM = 0
salM = 0
salH = 0

for pessoas in range(4):
  sal = 0
  sexo = input("Digite o seu sexo(M ou H): ")
  sal = float(input("Digite o seu salário: "))
  if sexo == 'm' or sexo == 'M':
    totalM = totalM+1
    salM = salM + sal

  elif sexo == 'h' or sexo == 'H':
    totalH = totalH+1
    salH = salH +sal

  else:
    print("Entrada inválida")

print(f"Número de Mulheres: {totalM} Total do salário: R$ {salM:.2f}")

print(f"Número de Homens: {totalH} do salário: R$ {salH:.2f}")