# -*- coding: utf-8 -*-
"""13.03.24 - Exemplo 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rpyTRO1Kd61tV7TQO1On2mePKOWZvVwa
"""



"""Estruturas de Decisão

 -Sempre prestar atenção na identação, comandos de reposta ao if devem
          estar sempre abaixo do if e com espaço

-Estrutura de decisão composta:
          
          if variável > 10:

               print("O número é maior que 10!")
          else:
   
              print("O número é menor ou igual a 10")

Enter+backspace: Fecha if

"""

num = 100

if num > 10:
  print("O número é maior que 10!")
else:
  print("O número é menor ou igual a 10")

"""-Estrutura Encadeada (else if)

            elif numm==10:
              print("O número é igual a 10")

- elif = else + if, estrutura de decisão encadeada
"""

num = int(input("Digite um número: "))

if num >10:
  print("O número %i é maior que 10" %num)
elif num==10:
  print("O número %i é igual a 10" %num)
else:
  print("O número %i é menor que 10" %num)