# -*- coding: utf-8 -*-
"""2-Exemplo 2 - EstruturasLista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zE-tn-IglE8nQk7bwyXj5M367WVRLfXU

Estruturas de Dados - Lista
"""

#declarando uma lista
idades=[]

#declarando e alocando valores em uma lista
idades=[20,30,55,60]
print(f"Imprimindo a lista: {idades}")

#declarando e alocando diferentes tipos de valores em uma lista
lista=['a',8,True,10.9,"Gabriel"]
print(f"\nImprimindo uma lista com diferentes tipos de dados: \n {lista}")

#acessando um elemento especifico da lista
print(f"\nAcessando um elemento da lista: {lista[4]}")

#acessando o primeiro elemento de trás para frente da lista
print(f"\nAcessando o primeiro elemento de trás para frente da lista: {lista[-1]}")

#criando uma lista dentro de outra lista
lista=['a',8,True,[100,200,300],10.9,"Gabriel"]

#acessando um elemento especifico da lista
print(f"\nAcessando um elemento da lista: {lista[3]}")

#acessando um elemento especifico de uma lista dentro de outra lista
print(f"\nAcessando um elemento de uma lista dentro de outra lista: {lista[3][2]}")

#armazenando grande quantidade de valores
nota=[]

for i in range(10):
  nota = float(input("Digite uma nota: "))
  nota.append(nota)

print(f"Notas: {nota}")

