# -*- coding: utf-8 -*-
"""Exemplos-Panda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_vWVkSs5DiV4fEiHTVHvbIvwceO1ji8
"""

#Biblioteca Panda

#Importando biblioteca panda
import pandas as pd

venda={'Data':['01/06/2024','04/06/2024'],'Valor':['500','300'],'Produto':['feijão','arroz'],'Quantidade':['10','20']}

#Criando uma tabela com a função "DataFrame"
venda_df = pd.DataFrame(venda)
print(venda_df)

#Vizualização com mais detalhes
display(vendas_df)

#Importando biblioteca panda
import pandas as pd

#Importando uma planilha do Execel
#Necessário fazer Upload do arquivo
vendas_pd = pd.read_excel("/baseDados.xlsx")

#Mostrando a tabela
#print("Tabela Vendas:")
#display(vendas_pd)


#Mostrando os três primeiros indices da tabela
print("Tabela Vendas:")
display(vendas_pd.head(3))


#Imprimindo o total de linhas
print("\n\nTotal de linhas:")
display(vendas_pd.shape)


#Descrevendo a tabela
print("\n\nDescrição da tabela:")
display(vendas_pd.describe())


#Imprimindo uma coluna
print("\n\nImprimindo a coluna Descrição:")
display(vendas_pd['Descrição'])

#Imprimindo uma coluna
print("\n\nImprimindo a coluna Descrição e Tipo:")
display(vendas_pd[['Descrição','Tipo']])

#Importando biblioteca panda
import pandas as pd

#Importando uma planilha do Execel
#Necessário fazer Upload do arquivo
vendas_pd = pd.read_excel("/baseDados.xlsx")

#Mostrando uma linha selecionada
print("Imprimindo dados da linha 0:")
display(vendas_pd.loc[0])

#Mostrando dados de mais de uma linha selecionada
print("\n\nImprimindo dados da linha 0 e 1")
display(vendas_pd.loc[0:1])


#Mostrando dados ENTRE linha 0 e linha 3
print("\n\nImprimindo dados entre linha 0 e linha 3")
display(vendas_pd.loc[0:3])


#Mostrando dados da linha 0 e linha 3 SOMENTE
print("\n\nImprimindo dados da linha 0 e linha 3")
display(vendas_pd.loc[[0,3]])

#Importando biblioteca panda
import pandas as pd

#Importando uma planilha do Execel
#Necessário fazer Upload do arquivo
vendas_pd = pd.read_excel("/baseDados.xlsx")


#Mostrando linhas através de uma condição
print("Imprimindo linhas com tipo RECEITA:")
display(vendas_pd.loc[vendas_pd['Tipo']=='Receita'])