# -*- coding: utf-8 -*-
"""1-Exemplo 1 - 03.04.2024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GlCTqJN_cy5Tjl__8_rcNPl9Vf_0lsr9

Lista-Métodos:
"""

lista = ['Linguagem C','Phyton','Cobol']
print(lista)
lista = [1,2,3,4]
print(lista)
type(lista)#tipo de dado

"""Criando uma lista a partir da função list()
        
         -nome da lista = list([dados da lista])
"""

#criando uma lista pela função list
lista = list(['a','b'])
print(lista)
type(lista)

"""Lista com for"""

#elevando os números da lista ao quadrado, começando por zero
lista = [item**2 for item in range(10)]
print(lista)

#elevando os números da lista ao cubo, dez vezes, começando por cem, indo de cinco em cinco
lista = [item**3 for item in range(10,100,5)]
print(lista)

#registrando apenas números pares na lista, começando por zero até vinte
lista = [numero for numero in range(20) if numero%2==0]
print(lista)


#registrando apenas números impares na lista, começando por zero até vinte
lista = [numero for numero in range(20) if numero%2!=0]
print(lista)

#imprimindo posições específicas da lista
lista = ['a','b','c','d']
print(lista[0])
print(lista[1])
print(lista[2])
print(lista[3])

#imprimindo posições específicas da lista
lista = ['a','b','c','d']
#último elemento da lista
print(lista[-1])
print(lista[3])
#penúltimo elemento da lista
print(lista[-2])

#lista com sublista
lista = [1,2,3,4,['a','b','c'],5,6]
print(lista)

#imprimindo primeiro elemento da sublista
print(lista[4][0])
#imprimindo a sublista
print(lista[4])

#incluindo número 22 no fim da lista
lista.append(22)
print(lista)
#incluindo letra X no começo da lista
lista.insert(0,'X')
print(lista)
#incluindo número 100 no fim da lista
lista.append(100)

print(f"Lista completa: {lista}")

#percorremdo uma lista e usando 'enumerate' para indicar as posições
lista = [1,2,3,4,['a','b','c'],5,6]
for indice, valor in enumerate(lista):
  print(f"Indice: {indice}, valor: {valor}")

lista = [1,2,3,4,['a','b','c'],5,6]
#recortando as posições começando por 3 até 5, contando de 1 em 1
print(lista[3:5:1])

lista = list(range(20))
print(lista)
print(lista[10:19])
print(lista[10:19:2])

lista=[41,12,3,4,99,5,6]
print(lista)
#ordenando a lista por ordem crescente
lista.sort()
print(lista)
#ordenando a lista por ordem inversa
lista.sort(reverse=True)
print(lista)
print(f'Maior valor da lista: {max(lista)}')
print(f'Menor valor da lista: {min(lista)}')
print(f'Tamanho da lista: {len(lista)}')
print(f'Soma dos elementos da lista: {sum(lista)}')

lista = [1,2,3,4,['a','b','c'],5,6]
print(lista)
#Removendo elementos da lista
#Removendo valor da primeira posição da lista
lista.pop(0)
print(lista)

#Removendo elemento especifico da lista
lista.remove(5)
print(lista)

