# -*- coding: utf-8 -*-
"""1-Exemplo 1 27.03.24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4tO1JBxhnNaJovtqcTGvYhjftSjUHD7

Estruturas de repetição - WHILE



-Repetição com flag: usado quando não sabemos o número exato de repetições
"""

cont = 0
idade = int(input("Digite a idade: "))
while idade != 999:
  idade = int(input("Digite a idade: "))
  cont+=1

print(f"Quantidade de pessoas: {cont}")

"""Faça um programa que calcule e mostre a média aritmética de N notas"""

nota = 0
med  = 0
cont = 0

while nota != 99:
  nota = float(input("Digite uma nota OU 99 para sair:"))
  if(nota != 99):
    cont+=1
    med += nota

if cont>0:
  print(f"Média das notas: {(med/cont):.2f}")
else:
  print("Sem notas cadastradas")

"""Uma academia deseja fazer um senso entre seus clientes para descobrir o mais alto, o mais baixo e o mais magro, para isto você deve fazer um programa que pergunte a cada um dos clientes da academia o seu código, sua altura e o seu peso. O final da digitação de dados deve ser dada quando o usuário digitar 0 (zero) no campo código. Ao encerrar o programa também deve ser informados os códigos e valores do cliente mais alto, mais baixo, do mais gordo e mais magro, além da média das alturas e pesos dos clientes."""

id = 0
id_magro = 0
id_gordo = 0
id_alto = 0
id_baixo = 0
peso = 0
alt = 0
cont = 0
maiorAlt = 0
menorAlt = 999
maiorPeso = 0
menorPeso = 999
medPeso = 0
medAlt = 0

while id != 999:
    id = input("\n \nDigite o seu código: ")
    if (id != 999):
      cont +=1
      peso = float(input("Digite o sua peso: "))
      alt = float(input("Digite a sua altura: "))
      medPeso += peso
      medAlt += alt

    if (alt>maiorAlt):
      maiorAlt = alt
      id_alto = id


    if (alt<menorAlt):
      menorAlt = alt
      id_baixo = id

    if (peso>maiorPeso):
      maiorPeso = peso
      id_gordo = id

    if (peso<menorPeso):
      menorPeso = peso
      id_magro = id



if(id == 999):
  print(f"Total clinetes: {cont}")
  print(f"Cliente mais alto: {maiorAlt} \n ID: {id_alto}")
  print(f"Cliente mais baixo: {menorAlt}\n ID: {id_baixo}")
  print(f"Cliente mais gordo: {maiorPeso}\n ID: {id_gordo}")
  print(f"Cliente mais magro: {menorPeso}\n ID: {id_magro}")
  print(f"Média de altura: {medAlt/cont}")
  print(f"Média de peso:   {medPeso/cont}")

