# -*- coding: utf-8 -*-
"""2-Exemplos 2 -15.05.24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wamLPCZmGu2tzaG5kh12u_cRFqjCLWPc
"""

#Vetores

#Importanto biblioteca
import numpy as np

#Criando uma lista e alocando os seus valores no vetor vet
lista=[1,2,3,4,5]
vet=np.array(lista)
print(type(vet))
print(vet)

#Matrizes

#Importanto biblioteca
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(matriz))
print(matriz)

#Importanto biblioteca
import numpy as np
vetDias = np.array(['segunda','terça','quarta','quinta','sexta','sabado','domingo'])
print(vetDias)
print(vetDias[4])
print(vetDias[6])

#Importanto biblioteca
import numpy as np
tupla=(1,2,3)
#Criando um vetor a partir de uma lista
vetNum = np.array(tupla)
print(type(vetNum))
print(vetNum)

#Importanto biblioteca
import numpy as np
vetNum= np.array([4,16,64,625])
print(vetNum)
print(f"Maior número do vetor: {max(vetNum)}")
print(f"Menor número do vetor: {min(vetNum)}")
print(f"Soma número do vetor: {sum(vetNum)}")
print(f"Quantidade de números do vetor: {len(vetNum)}")
print(f"Mediana dos números do vetor: {np.median(vetNum)}")
print(f"Média de números do vetor: {np.mean(vetNum)}")
print(f"Raíz quadrada dos números do vetor: {np.sqrt(vetNum)}")