# -*- coding: utf-8 -*-
"""Exercicio-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18O3Dz6isi3tOQu633-sA-EY57B-nW2k_

1-Faça um programa que calcule a média de um aluno a partir de cinco notas previamente cadastradas em uma lista
           
           -Utilize as notas: 6,7,6.5,4.8,8


2- Criar um programa em Phyton que soliciteai usuário o nome de 5 pessoas e armazenar em uma lista. Em seguida, o programa deve classificar os nomes de modo ascendente e solicitar ao usuário um número de 0 a 4, correspondendo ao indíce, e o programa deverá mostrar o nome armazenado nesse indice


3-Criar um programa em Phyton que solicite ao usuário o nome de 5 pessoas, armazene em uma lista e exibe os nomes digitados e o tamanho da lista. Em seguida o programa deve solicitar ao usuário um nome, e o programa deverá remover o nome armazenado na lista, exibir os nomes digitados e o tamanho da lista

4-Faça um programa em Phyton que contenha 3 listas com os nomes: valores, par e impar. Solicite N números inteiros ao usuário e armazene-os na lista chamada valores (utilize o critério de parada o valor digite 999). Após  a obtenção dos dados, na lista par armazenar os pares, e na lista impar os números impares. Exibe os números armazenados nas 3 listas
"""

#Exercicio 1
notas = [6,7,6.5,4.8,8]
print(f"Notas: {notas}")
print(f"Média {((sum(notas))/6)}")

#Exercicio 2
nomes = list()
for cont in range(5):
  nome = input("Digite o nome: ")
  nomes.append(nome)

for indice, valor in enumerate(nomes):
  nomes.sort()
  print(f"Indice: {indice}, nomes: {nomes[indice]}")


num=int(input("Digite um número:"))
print(nomes[num])

#Exercicio 3
nomes = list()
for cont in range(5):
  nome = input(f"{cont}-Digite um nome:")
  nomes.append(nome)

print(f"Nomes digitados: {nomes}")
print(f"Tamanho da lista: {len(nomes)}")

nome = input("Digite um nome para apagar: ")
nomes.remove(nome)
print(f"Nomes restantes: {nomes}")
print(f"Tamanho da lista: {len(nomes)}")

#Exercicio 4
valores = list()
par = list()
impar = list()
cont = 0
val = 0

while val != 999:
  val = int(input(f"{cont}-Digite um número: "))
  if (val != 999):
    cont = cont+1
    valores.append(val)
    if (val%2==0):
        par.append(val)
    elif (val%2!=0):
        impar.append(val)


if (cont == 0):
   print("Não foram inseridos números válidos")

else:
  print(f"Valores: {valores}")
  print(f"Valores pares: {par}")
  print(f"Valores impares: {impar}")