# -*- coding: utf-8 -*-
"""Conjunto 6ª.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4vWeXU4XJp77WFDr83BUs35VtTmmB0u
"""

#Conjunto ==> set representado por {}
#não confundir com dicionário {chave:valor}
#vou chamar de cj um conjunto
cj={1,2,3,4}
print (type(cj))

cj=set({'Amarelo','Azul'})
type (cj)
print (cj)

frutasVermelhas={'Morango','Acerola','Melancia'}
frutasAmarelas={'Manga','Pessego','Banana','Acerola'}
#união de conjuntos
frutas=frutasVermelhas | frutasAmarelas
print(frutas)
#intersecção de conjuntos
frutas=frutasVermelhas & frutasAmarelas
print(frutas)
#tamanho do conjunto
print (f"Total de elementos: {len(frutas)}")

frutasVermelhas={'Morango','Acerola','Melancia'}
frutasAmarelas={'Manga','Pessego','Banana','Acerola'}
frutas=frutasVermelhas | frutasAmarelas
#ATENÇÃO /*/*/*/*/*/*/*/
print (f"Total de elementos: {len(frutas)}")

frutasVermelhas={'Morango','Acerola','Melancia'}
#ACESSANDO OS ELEMENTOS - não pode ser por índice
print (frutasVermelhas[2])

frutasVermelhas={'Morango','Acerola','Melancia'}
#só podemos acessar iterando.
for xxx in frutasVermelhas:
  print(xxx)

frutasVermelhas={'Morango','Acerola','Melancia'}
frutasVermelhas=list(frutasVermelhas)
print (frutasVermelhas)
#só podemos acessar iterando.
lista=[]
for fruta in frutasVermelhas:
  lista.append(fruta)

print(lista)

