# -*- coding: utf-8 -*-
"""1-Exercicios - 10.04.2024-TUPLAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162USkmgL-pcRQ5ELUtIsFqrWDBonxOy_

1-Faça um programa que leia duas listas e gere um terceira coms os elementos das duas primeiras


2-Crie uma tupla preenchida com os 10 primeiros colocados do campeonato paulista de futebol de 2024, em ordem de colocação, depois:

        - Os 3 primeiros colocados
        - Os 3 últimos colocados
        - Os times em ordem alfabética
        - A posição que o Santos terminou no campeonato


3-Carregar um tupla com os dias da semana. Em seguida peça para o usuário para digiter um número de 1 a 7 e então mostre o dia da semana.
"""

#Exercicio 1
par = [0,2,4,6,8,10]
impar = [1,3,5,9,11]
print(f"Números pares: {par}")
print(f"Números impares: {impar}")
numeros = par+impar
print(f"União das listas: {numeros}")

#Exercicio 2

times = ('Palmeiras','Santos','Bragantino','São Paulo','Novorizontino','São Bernardo','Inter de Limeira', 'Ponte Preta','Agua Santa','Corinthians')
i = 0
print("Classificação:")
for i in range(10):
  print(f"{i+1} - {times[i]}")

print(f"Lideres de classificação: {times[0:3]}")
print(f"Últimos colocados : {times[7:10]}")
print(f"Ordem alfabética dos times: {sorted(times)}")
print(f"Posição do Santos: {times.index('Santos')+1}")

#Exercicio 3

semana = ('Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sabado')
x  = int(input("Digite um número: "))
print(f"Dia da semana: {semana[x-1]}")