# -*- coding: utf-8 -*-
"""Exercícios .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ST4LAQhh219eYKfjME3NdDajI-VnB2Q6

-Exercicios

-1) Faça um programa que exiba seu nome na tela

-2)Escreva um programa que exiba o resultado de 2a x 3b, em que A vale 3 e b vale 5

-3) Escreva um programa em Python que solicite ao usuário a distância entre duas cidades e o tempo de viagem. O programa deverá calcular e exibir a velocidade média de um carro que vai de uma cidade para outra. Utilize a fórmula: velMedia = distancia / tempo

-4) Escreva um programa em Python que leia um valor representando o gasto realizado por um cliente do restaurante ComaBem e visualize o valor total a ser pago, considerando os 10% do garçom.

-5) Desenvolva um programa em Python que solicite ao usuário os valores dos lados de um retângulo e calcule e mostre seu perímetro e sua área.

-6) Escreva um programa em Python que solicite ao usuário o salário atual e mostre o salário acrescido de 5% de comissão.

-7) Escreva um programa que calcule a soma de três variáveis e imprima o resultado na tela.
"""

#Exercicio 1
nome=input("Digite o seu nome: ")
print("Nome digitado: %s" %nome)

#Exercicio 2
a=3
b=5
print("Resultado de %i x %i = %i" %(a,b,a*b))

#Exercicio 3
distancia=input("Digite a distâancia entre as cidades:")
tempo=input("Digite o tempo(em minutos) de viagem : ")
distancia=int(distancia)
tempo=int(tempo)
print("Velocidade média: %.1f" %(distancia/tempo))

#Exercicio 4
conta=input("Digite o valor pago: ")
conta=float(conta)
print("Total: %.2f" %((conta*0.10)+conta))

#Exercicio 5
lado=input("Digite o lado de um triângulo: ")
lado=int(lado)
print("Perimetro: %i ² =  %i" %(lado,lado*lado))
base=input("Digite a base de um triângulo:")
altura=input("Digite a altura de um triângulo:")
base=float(base)
altura=float(altura)
print("Área do triângulo: %.1f x %.1f / 2 = %.2f" %(base,altura,(base*altura)/2))

#Exercicio 6
salario=input("Digite o salario:")
salario=float(salario)
print("Total: %.2f" %((salario*0.05)+salario))

#Exercicio 7
val1=input("Digte o primeiro valor: ")
val2=input("Digte o segundoi valor: ")
val3=input("Digte o terceiro valor: ")
val1=int(val1)
val2=int(val2)
val3=int(val3)
print("Soma de %i + %i + %i = %i" %(val1,val2,val3,(val1+val2+val3)))