# -*- coding: utf-8 -*-
"""Dicionario 4ª manha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCUzhqUdIqN8AXaNoZxvuI6PzvoVnUC0
"""

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}
print(type(dic))

#alterando o conteúdo
dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde",
     "cor5":"azul","cor1":"vermelho"}
print(dic)

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}
#acessar os elementos do dicionário
print(dic)
print(dic.keys())
print(dic.values())

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}
#incluindo uma nova cor
dic["cor5"]="ciano"
dic["cor6"]="marrom"
print(dic)

#alterar o conteúdo de uma cor
dic["cor1"]="laranja"
print(dic)

#atribuindo um valor de um item
#do dicionário a uma variável
valor=dic["cor1"]
print(valor)
valor=dic.get("cor2")
print(valor)

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}
print(dic)
print(dic.keys())
print(dic.values())
print(dic.items())

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}
for cor in dic:
  print(cor)
#ou
for cor in dic.keys():
  print(cor)

for cor in dic.values():
  print(cor)

for cor in dic.items():
  print(cor)

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}

del dic["cor1"]  #exclusão pelo índice
valor_excluido=dic.pop("cor4") # nome dic.método()
print(f"Item excluído: {valor_excluido}")
print(dic)
dic.clear()   #exclui TODOS OS ITENS
print(dic)

dic={"cor1":"azul","cor2":"amarelo",
     "cor3":"rosa","cor4":"verde"}
print(f"Número de itens: {len(dic)}")

#1)Crie um dicionário que represente as notas de um estudante em
#várias disciplinas.Calcule a média das notas e imprima-a na tela.
#Adicione uma nova disciplina e sua nota ao dicionário
# e recalcule a média.
notas = {"Português":5,"Matemática":9,"Física":2}
somaNotas=0
notas["Química"]=10
for nota in notas.values():
  somaNotas=somaNotas+nota

print(f"Média = {somaNotas/len(notas):.2}")

frutas={"maçã":10,"abacate":15,"melão":3,
        "melancia":1}
print(frutas.keys())
frutaUsuario=input("Fruta:")
if frutaUsuario in frutas:
  print(frutas.get(frutaUsuario))
else:
  print("Fruta não cadastrada!")

contagem_numeros = {}    #dicionário vazio
numeros = [1, 2, 3, 2, 4, 5, 1, 3, 2, 1, 5, 5]   #lista

# Iterar pela lista e contar as ocorrências de cada número
for numero in numeros:
    if numero in contagem_numeros:
        contagem_numeros[numero] += 1    #adicionando no dicionário contagem_numeros
    else:
        contagem_numeros[numero] = 1