# -*- coding: utf-8 -*-
"""Exemplo 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14rZ0WqxTzmCgryS0jL7VLprm6RZVtCNU
"""



"""Conceitos básicos
Phyton
"""

#comentario no Phyton "#"
#comando de saída
#print("Trabalhando com Python")
#print('Novamente imprimindo')
print("2000+155")
print("Resultado = ",2000+155)

"""Operadores Aritméticos

-Soma +

-Multiplicação *

-Subtração -

-Divisão:

*  Divisão Normal /
*  -Divisão Inteira //
*  -Resto %

-Exponenciação **
"""

print("divisão normal = 1500 / 2.3 =",1500/2.3)
print("divisão inteira = 1500 // 2.3 = ",1500//2.3)
print("divisão resto = 1500 % 2.3 = ",1500%2.3)

print("Exponenciação = 2^5 = ",2**5)

"""Operadores Relacionais

-Maior >

-Menor <

-Maior ou igual >=

-Menor ou igual <=

-Igual ==

-Diferente !=

-Sempre que trabalharmos com operaradores relacionais, os resultados serão booleanos (True or False)
"""

print(5>4)
print(5==4)
print(5!=4)