# -*- coding: utf-8 -*-
"""Exemplos-22.05.24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BpZG94ghWicXuHKVP8Jm4q476fBmmpT
"""

#Vetor = estrutura especial
#Armazena dados do mesmo tipo
#Utiliza a biblioteca numpy

import numpy as np
#"np" - abreviação de np

#Criando uma lista para transformar em vetor
lista = [10,11,12,13,14]
vetor = np.array(lista)

print(type(vetor))
print(f"Lista: {lista}")
print(f"Vetor: {vetor}")

#Convertendo vetor para lista
lista2=list(vetor)
vetor = np.array(lista2)

import numpy as np

lista = ['a','b','c','d','e']
vetor = np.array(lista)

print(f"Vetor: {vetor}")
print(f"Posição 0: {vetor[0]}")
print(f"Posição 4: {vetor[4]}")
print(f"Posição -1: {vetor[-1]}")
print(f"Posição -2: {vetor[-2]}")

import numpy as np

tupla=(10,20,30,40)
vetor=np.array(tupla)

print("Imprimindo posições do vetor:")
for numero in range(len(vetor)):
    print(numero)

print("Imprimindo conteúdo do vetor:")
for numero in vetor:
    print(numero)

import numpy as np
#Criando vetor vazio
vetor=np.array([])

for num in range(5):
  vetor = np.append(vetor,int(input("Digite um número:")))

print(f"Vetor: {vetor}")
#Ordenando vetor
vetor.sort()
print(f"Vetor ordenado: {vetor}")
#Invertendo os INDICES de um vetor
np.flip(vetor)
print(f"Vetor ordenado ao contrário: {vetor}")

import numpy as np

lista = [1,2,3,4,5]
vetor = np.array(lista)

print(f"Vetor: {vetor}")
print(f"Soma das posições 2 e 3: {vetor[2]+vetor[3]}")

import numpy as np

vetor = np.array([1,2,3,4,5])
print(vetor)
#Inserindo valores no vetor
vetor = np.append(vetor, 100)
print(vetor)
vetor = np.append(vetor, 0)
print(vetor)

#Excluindo valores de um vetor
#Excluindo valor da posição 0
vetor = np.delete(vetor,0)
print(vetor)

#Alterando valor de uma posição
vetor[0]= 200
print(vetor)

import numpy as np

vetor = np.array([1,2,3,4,5])
print(f"Vetor: {vetor}")
print(f"Maior valor: {max(vetor)}")
print(f"Menor valor: {min(vetor)}")
print(f"Soma dos valores: {sum(vetor)}")
print(f"Indices do vetor: {len(vetor)}")
print(f"Média: {(sum(vetor))/len(vetor)}")
print(f"Média-Outra forma: {np.mean(vetor)}")
print(f"Raíz quadrada: {np.sqrt(vetor)}")

import numpy as np


vetor = np.array([1,2,3,])
vetor2 = np.array([4,5,6])
#Somando cada indice do vet1 com o indice
#correspondente no vet2
vetor3 = vetor+vetor2
vetor4 = vetor-vetor2
vetor5 = vetor*vetor2
print(vetor)
print(vetor2)
print(vetor3)
print(vetor4)
print(vetor5)