# -*- coding: utf-8 -*-
"""1-Exercicio 1 - 20.03.24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6xsLIo7AXEzUbb4v3n47_or4YubwrvN

1-Exercio: Escreva um programa para ler a nota de 10 alunos e contar quantos foram aprovados, sendo que, para ser aprovado, a nota deve ser maior ou igual a 6,0. Escreva número de aprovados
"""

#Exercicio 1
cont = 0
contre = 0

for i in range(4):
  nota = float(input("Digite a nota do aluno: "))

  if nota >= 6:
    cont = cont + 1

  else:
    contre = contre +1

print(f"Alunos aprovados: {cont}")
print(f"Alunos reprvoados: {contre}")

"""2-Exercicio: Faça um programa para ler o código e o preço de 15 produtos, calcular e escrever:
      -o maior preço lido
      -a média aritmética dos preços dos produtos
"""

#Exercicio 2
med = 0
maior = 0
menor = 9999999

for i in range(4):
  prec = 0
  id = int(input(f"Digite o código do produto x{i+1}: "))
  prec = float(input("Digite o preço do produto: "))
  if prec > maior:
    maior = prec

  if prec < menor:
    menor = prec

  med += prec

med = (med/(i+1))
print(f"Média: {med}")
print(f"Maior preço: {maior}")
print(f"Menor preço: {menor}")

"""3-Exercicio: Cadastrar o salario de 10 pessoas. Exibir o número de mulheres que ganham mais que 5000.  Exibir o número de homens que ganham menos que 200"""

#Exercicio 3:
contF = 0
contM = 0

for i in range(4):
  sexo = input("Digite o seu sexo: ")
  sal = float(input("Digite o seu salario: "))

  if sexo == 'F' or sexo == 'f' and sal > 5000:
    contF += 1

  elif sexo == 'M' or sexo == 'm 'and sal < 2000:
    contM += 1

print(f"Mulheres que ganham mais de R$ 5000: {contF}")

print(f"\nHomens que ganham menoss de R$ 2000: {contM}")