# -*- coding: utf-8 -*-
"""Exemplo 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VQcw6BPag7Wd-xaCkz5W40c7WQ5nyoNj

Variáveis de Memória

-String :  nome = 'Gabriel'  
-Int :     idade = 19        
-float:     salario = 1200.50
-booleano:  temFilhos = False
"""

nome = 'Gabriel'
idade = 19
salario = 1200.50
temFilhos = False

#exibindo com concatenação
print(nome,"tem",idade,"anos e ganha R$",salario)

#exibindo com estrutura de dados
print("%s tem %i anos e ganha R$ %.2f" %(nome,idade,salario))

"""Entrada de dados

-Toda informação digitada entra como string

-Comando de entrada de dados: input()

-Converter string (Casting):  

1.   Para int: variavel=int(variavel)
2.   Para float: variavel =float(variavel)


"""

nome=input("Digite um nome:")
print("Nome digitado: %s" %nome)
anoNasc=input("Digite o ano de nascimento: ")

#Fazendo casting
anoNasc=int(anoNasc)
print("Ano de Nascimento: %i" %anoNasc)