# -*- coding: utf-8 -*-
"""1-Exemplos 1 -15.05.24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12CAL9zIOIyDIIXQhxt3gXEOKKsc2F-_q
"""

#ESTRUTURA DE DADOS - CONJUNTO
#Conjunto é uma coleção não ordenada
#Imutável (conseguimos exlucir e inserir)
#Imutável = só não consigo alterar o que já está inserido
#Não indexada

cj={1,2,3,4}
print(type(cj))
print(cj)





#Função set
cj=set({'Amarelo','Azul'})
print(type(cj))
print(cj)

frutasVermelhas={'Morango','Acerola','Melancia'}
frutasAmarelas={'Manga','Pessego','Banana','Acerola'}

#união de conjuntos
frutas = frutasVermelhas | frutasAmarelas
print(frutas)
#ou
frutas1 = frutasVermelhas.union(frutasAmarelas)
print(frutas1)

#intersecção
frutas2 =  frutasVermelhas & frutasAmarelas
print(frutas2)
#ou
frutas3 = frutasVermelhas.intersection(frutasAmarelas)
print(frutas3)

#tamanho do conjunto
print(f"Total de frutas: {len(frutas)}")
print(f"Total de frutas vermelhas: {len(frutasVermelhas)}")
print(f"Total de frutas amarelas: {len(frutasAmarelas)}")

frutasVermelhas={'Morango','Acerola','Melancia'}
#só podemos acessar iterando

for frutas in frutasVermelhas:
  print(frutas)

#armazenando em uma lista
lista = []
for fruta in frutasVermelhas:
  lista.append(fruta)
print(lista)


lista1 = list(frutasVermelhas)
print(lista1)

#Removendo valores
frutasVermelhas={'Morango','Acerola','Melancia'}
frutasVermelhas.remove('Acerola')
print(frutasVermelhas)

#Adicionando
frutasVermelhas.add("Maçã")
print(frutasVermelhas)